#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         5
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a term state=pseudo_tiled follow=on
bspc rule -a Telegram-desktop desktop='^9' state=pseudo_tiled follow=on
bspc rule -a Firefox desktop='^3' state=pseudo_tiled follow=on
