#!/bin/bash

set -e

scripts_dir="$HOME/.config/vbar/scripts"

vbar=$(which vbar 2> /dev/null || "~/projects/vbar/vbar")

$vbar add-css --class bar --css "font-family: Hack;"
$vbar add-css --class bar --css "font-weight: normal;"
$vbar add-css --class bar --css "font-size: 14px;"
$vbar add-css --class bar --css "text-shadow: none;"
$vbar add-css --class bar --css "background-color: #1b202a;"
# $vbar add-css --class bar --css "border: 0px solid #1b202a;"

$vbar add-css --class block --css "padding-top: 1px;"
$vbar add-css --class block --css "padding-bottom: 1px;"
$vbar add-css --class block --css "padding-left: 10px;"
$vbar add-css --class block --css "padding-right: 10px;"
$vbar add-css --class block --css "color: #9aa7bd;"
$vbar add-css --class block --css "background-color: #323c4d;"

$vbar add-css --class menu --css "font-family: Hack;"
$vbar add-css --class menu --css "font-weight: normal;"
$vbar add-css --class menu --css "font-size: 16px;"
$vbar add-css --class menu --css "text-shadow: none;"
$vbar add-css --class menu --css "background-color: #323c4d;"
$vbar add-css --class menu --css "color: #9aa7bd;"
$vbar add-css --class menu --css "border: 10px solid #323c4d;"

$vbar add-css --class "menu :hover" --css "background-color: #232936;"
$vbar add-css --class "menu :hover" --css "color: #9aa7bd;"

$vbar add-css --class power-off-icon --css "font-family: \"Font Awesome\";"
$vbar add-css --class power-off-icon --css "background-color: #232936;"

$vbar add-css --class title --css "background-color: #1b202a; font-size: 10px;"

$vbar add-css --class battery-icon --css "font-family: \"Font Awesome\";"
$vbar add-css --class battery-icon --css "background-color: #232936;"

$vbar add-css --class battery --css "margin-right: 10px;"

$vbar add-css --class volume-icon --css "font-family: \"Font Awesome 5 Free\";"
$vbar add-css --class volume-icon --css "background-color: #232936;"

$vbar add-css --class volume --css "margin-right: 10px;font-family: \"Font Awesome 5 Free\";"

$vbar add-css --class net-icon --css "font-family: \"Font Awesome 5 Free\";"
$vbar add-css --class net --css "margin-right: 10px;"

$vbar add-css --class date --css "margin-right: 10px;"

$vbar add-css --class time --css "margin-right: 0px;"

$vbar add-css --class temp --css "background-color: #ff00ff"

$vbar block add --left --name power-off-icon --text ""

$vbar add-menu --name power-off-icon --text "Log off" --command "bspc quit"
$vbar add-menu --name power-off-icon --text "Shut down" --command "systemctl poweroff"

read -r -a desktops <<< $(xprop  -root _NET_DESKTOP_NAMES | sed 's/\(.*\=\)\|\(\,\)\|\("\)//g')
for desktop in ${!desktops[@]}; do
	$vbar add-css --class "desktop-$desktop" --css "background-color: #1b202a;"
	$vbar add-css --class "desktop-$desktop" --css "letter-spacing: 10px;"
	with_client="⊙"
	without_client="○"
	check_clients="$scripts_dir/is_clients_on_desktop.sh $desktop && echo $with_client || echo $without_client"
	check_desktop="$scripts_dir/is_desktop.sh $desktop"
	command="$check_desktop && $vbar add-css --class \"desktop-$desktop\" --css \"background-color: #354555\" || $vbar add-css --class \"desktop-$desktop\" --css \"background-color: #1b202a\" && $check_clients"

	$vbar block add --left --name "desktop-$desktop" --command "$command" --tail-command "$scripts_dir/desktop_spy.sh | while read r; do $vbar update --name \"desktop-$desktop\" ; done" --click-command "wmctrl -s $desktop"
done

$vbar block add --center --name title --tail-command "xtitle -s"

$vbar block add --right --name volume --command "[[ \$($scripts_dir/volume_state.sh) = on ]] && icon='' || icon='' && echo \$icon \$($scripts_dir/volume_val.sh)%" --click-command "pamixer -t && $vbar update --name volume" --interval 5

if [[ $(acpi 2>&1) != "No support for device type: power_supply" ]] ; then
	$vbar block add --right --name battery-icon --text ''
	$vbar block add --right --name battery --tail-command "while true; do acpi | cut -d, -f2 | sed 's/ //'; sleep 5; done"
fi
net_type=${scripts_dir}/net_type.sh

$vbar block add --right --name "net-icon" --command "test \$($net_type) = ethernet && echo '' || echo ''"
sleep 1
$vbar block add --right --name "net" --command "$scripts_dir/net_address.sh \$($scripts_dir/net_device.sh) && $vbar update --name net-icon" --interval 5

$vbar block add --right --name date --command "date +%d/%m" --interval 60
$vbar block add --right --name time --command "date +%H:%M" --interval 1
